### ISSUE TITLE
Release 6.1.0

### ISSUE THREAD

**Issue by kevin-bates** [jupyter/notebook#5423]
There have been some pull requests merged (and others waiting) that probably warrant more than a patch release, so I'd like to start the process of putting things together for a Notebook 6.1.0 release.  Preferably, this would be based on master.

Here are the [commits since 6.0.3](https://github.com/jupyter/notebook/compare/6.0.3...master), most of which came with #4479 - which is a primary reason for introducing a minor release. 

Other PRs I think we should include - although I don't necessarily expect all these to make the release...
- [x] Add ability to cull terminals and track last activity #5372 (Zach, reviewed)
- [x] Add UNIX socket support to notebook server. #4835 (Steve)
- [x] ~~[WIP] Make the last modified date consider files in subdirectory #5336 **(front-end review required)**~~ (Zach, won't be ready in the near future).
- [x] Added nl language #5354
- [x] tree added download multiple files #5351 **(front-end review required)** (Zach)
- [x] Readme viewer #5299  **(front-end review required)** (Zach, discuss at next meeting)
- [x] Make a notebook writable after successful save-as #5296  **(front-end review required)** (Darian)
- [x] ~implement natural sorting fixes 5230 #5259 **(front-end review required)** (Darian: changes requested)~ (deferred to next release)
- [x] Add env variable support for port options #5221 (Steve)
- [x] Update CodeMirror dependency #5198 **(front-end review required)** (Steve)
- [x] Toolbar buttons tooltip: show help instead of label #5107 **(front-end review required)** (Darian) 
- [x] kill notebook its self when server cull idle kernel #5593  **(front-end review required)** (Zach—approved, waiting for reply since tests are failing)
- [x] ~Adjust buffer replay logic for restarts w/ new ports #5450~ (deferred to jupyter_server)
- [x] Added functionality to allow filter kernels by Jupyter Enterprise Gat… #5484 (Kevin)
- [x] Bump minimum version of jQuery to 3.5.0 #5491 (Kevin)
- [x] (Issue) Backspace doesn't delete empty line #5502
- [x] Update changelog (Kevin) - ([latest updates](https://github.com/jupyter/notebook/commit/6b824f69b83a545f0cbebd984c7a8eb66065ece9))
- [x] Improve login shell heuristics #5588
- [x] Add support for `JUPYTER_TOKEN_FILE` #5587 (Kevin)
- [x] Russian I18N support #5571 (Kevin)
- [x] Paste two images #5598 **(front-end review required)** (Steve)
- [x] Add a metadata tag to override notebook direction (ltr/rtl) #5052 (Steve)
- [x] Add keyboard shortcuts to menu dropdowns #5525 (Steve)
- [x] Resolve CodeMirror version issue (5.53.2 vs. 5.55+) #5629 (Steve,Kevin)

If there are other issues and/or pull requests you'd like to see in a 6.1.0 release, please add comments and I'll amend this text - or feel free to amend this yourself (if privs allow).

**Comment by willingc** [comment]
@blink1073 @kevin-bates Would it be possible to release a 6.0.4 with minimally the fix for #4835 which prevents installing in a Python 3 virtual environment? Installing `requests-unixsocket` would not resolve the install failure. Pulling master and building from HEAD worked.

Alternatively, 6.1 would be great too. :smile:

**Comment by kevin-bates** [comment]
Hi @willingc - thanks for the heads up.  

I'm a little confused in trying to understand your comment from an urgency perspective.  Neither #4835 nor the fix I believe you're referring to (#5451) have been released - both in master waiting for their "carrier".  So was your py3 installation issue the result of cherry-picking #4853 (having not also taken #5451)?

Our intention is to build 6.1 from master but if there's more at play here I suppose we could look into an interim patch release.  Although, having never built a notebook release, I should defer to Steve on that.

I was going to suggest at least one rc release (for 6.1) so we can discover, and workout, any kinks as well.

**Comment by kevin-bates** [comment]
Release 6.1.0rc1 has been pushed to PyPI.  Does conda-forge handle pre-releases?  If so, I'd prefer to wait to announce the RC. 

I was going to post in the google groups, gitter, and discourse forums.  Are there other locations?

**Comment by blink1073** [comment]
Thanks!

Pre-releases on conda are possible: I added an [`rc` branch](https://github.com/conda-forge/notebook-feedstock/tree/rc) to the feedstock.
Here is an example rc PR from JupyterLab: https://github.com/conda-forge/jupyterlab-feedstock/pull/206
And the JuptyerLab branch: https://github.com/conda-forge/jupyterlab-feedstock/tree/rc

I think those ANN locations sound good.

**Comment by kevin-bates** [comment]
Thanks Steve!  I've submitted https://github.com/conda-forge/notebook-feedstock/pull/68 targeting the rc branch and based on the jupyterlab example.

**Comment by kevin-bates** [comment]
@Zsailer, @blink1073, @afshin - could you please review the set of unmarked tasks above?  I think we need to try to get 6.1 out soon (preferably next week) and I believe the unmarked items are ready (with the exception of #5259).

Also, Steve, I noticed you marked some of these with a 6.2 milestone and I suspect that was to prevent 'feature creep'.  Just wondering your thoughts on including them in 6.1?

I'd like to go ahead and include the Russian I18N work since that's the kind of thing that shouldn't be too disruptive if there are issues that were not caught in review.  Any objections?

**Comment by blink1073** [comment]
I just didn't want to step on your toes.  I merged the ones that were waiting in the wings.

**Comment by Zsailer** [comment]
Thank you for championing this forward, @kevin-bates! I merged #5593. 

I would think we should bump #5259 to 6.2, since there hasn't been activity on that PR in awhile.

> I'd like to go ahead and include the Russian I18N work since that's the kind of thing that shouldn't be too disruptive if there are issues that were not caught in review. Any objections?

:+1: I agree!

**Comment by afshin** [comment]
I agree with Zach. If they do not come back to update it, I can take a more serious look at that PR if we think it's important and we can put it in 6.2.

**Comment by kevin-bates** [comment]
Thank you for your timely responses and all your help!  I'll finalize the changelog and let things sit for a day or so, then release 6.1.0 GA.

**Comment by kevin-bates** [comment]
6.1.0 is released - thank you all for your help with this!
